# Generated by Django 4.1.4 on 2022-12-29 23:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Services',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('choice_field', models.CharField(choices=[('NF', 'Netflix'), ('AP', 'Amazon Prime Video'), ('SP', 'Star+'), ('PM', 'Paramount')], max_length=2)),
            ],
        ),
    ]
