# Generated by Django 4.1.4 on 2022-12-28 12:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payment_user', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='payments',
            table='Payments',
        ),
    ]
