# Generated by Django 4.1.4 on 2022-12-28 13:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payment_user', '0003_alter_payments_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='payments',
            table=None,
        ),
    ]
