# Generated by Django 4.1.4 on 2022-12-29 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment_user', '0004_alter_payments_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='payments',
            name='expiration_date',
            field=models.DateField(default='2023-01-01'),
        ),
    ]
