# Generated by Django 4.1.4 on 2022-12-29 13:24

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment_user', '0005_payments_expiration_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payments',
            name='expiration_date',
            field=models.DateField(default=datetime.date(2023, 1, 1)),
        ),
    ]
